<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmacyContracts.Modules.Claims.Application\PharmacyContracts.Modules.Claims.Application.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Claims.Domain\PharmacyContracts.Modules.Claims.Domain.csproj" />
    <ProjectReference Include="..\PharmacyContracts.SharedKernel\PharmacyContracts.SharedKernel.csproj" />
  </ItemGroup>

</Project>
