<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Hangfire.AspNetCore" Version="1.8.24" />
    <PackageReference Include="Hangfire.SqlServer" Version="1.8.24" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.10" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.10">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PharmacyContracts.Modules.Auth.Api\PharmacyContracts.Modules.Auth.Api.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Auth.Application\PharmacyContracts.Modules.Auth.Application.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Auth.Infrastructure\PharmacyContracts.Modules.Auth.Infrastructure.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Companies.Api\PharmacyContracts.Modules.Companies.Api.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Companies.Application\PharmacyContracts.Modules.Companies.Application.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Companies.Infrastructure\PharmacyContracts.Modules.Companies.Infrastructure.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Sales.Api\PharmacyContracts.Modules.Sales.Api.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Sales.Application\PharmacyContracts.Modules.Sales.Application.csproj" />
    <ProjectReference Include="..\PharmacyContracts.Modules.Sales.Infrastructure\PharmacyContracts.Modules.Sales.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\" />
  </ItemGroup>

</Project>
